services:
  blog-app:
    image: devsecops-blog:latest
    container_name: blog-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=app.py
      - APP_NAME=flask-recettes
      - APP_VERSION=1.0
      - APP_MODE=prod       
      - FLASK_DEBUG=false
      