name: Docker Image Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Dockerfile configuration with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Build Docker image
        run: docker build -t devsecops-blog:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-blog:latest'
          format: 'table'
          exit-code: '1' 
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true # Ignore les failles sans correctif disponible