name: Docker Image Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-blog:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: devsecops-blog:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
