name: Lab 4 - DAST & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dast-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-blog:latest .

      - name: Start application with Docker Compose
        run: docker compose up -d 

      - name: Wait for application to be ready
        run: |
          echo "Waiting for app to start on Nginx router (port 8080)..."
          for i in {1..10}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "App is up!"
              exit 0
            fi
            echo "Attempt $i/10 - not ready yet..."
            sleep 3
          done
          exit 1

      - name: Run Wapiti DAST scan
        continue-on-error: true
        run: |
          sudo apt-get update && sudo apt-get install -y wapiti
          # On scanne directement le routeur sur le port 8080
          wapiti -u http://localhost:8080 -f html -o wapiti-report.html

      - name: Stop application container
        if: always()
        run: docker compose down

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push to DockerHub
        if: github.event_name == 'push'
        run: |
          REPO=${{ secrets.DOCKERHUB_USERNAME }}/devsecops-blog
          docker tag devsecops-blog:latest $REPO:latest
          docker tag devsecops-blog:latest $REPO:${{ github.sha }}
          docker push $REPO:latest
          docker push $REPO:${{ github.sha }}