name: SAST & SCA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast-sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit pip-audit 
          pip install semgrep

      - name: SAST — Bandit
        run: bandit -r . -x ./.venv,./static,./templates --severity-level medium -f txt
        continue-on-error: true

      - name: SAST — Semgrep
        run: semgrep scan --config auto .
        continue-on-error: true

      - name: SCA — pip-audit
        run: pip-audit -r requirements.txt